server:
  applicationConnectors:
    - type: http
      port: 9002
  adminConnectors:
    - type: http
      port: 9003
logging:
  level: INFO
authentication:
  login: admin
  password: password
database:
  name: usersAmad
userApi: http://localhost:9000/user
period:
  zodiac: 10
  birth: 5